default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 'tenanta'  # Update this line with the new password
  host: localhost
  port: 5432

development:
  <<: *default
  database: tenanta
  username: postgres
  password: 'tenanta'  # Update this line with the new password
  host: localhost
  port: 5432

test:
  <<: *default
  database: tenanta

production:
  <<: *default
  database: tenanta
  username: postgres
  password: <%= ENV['DATABASE_PASSWORD'] %>
